# .sops.yaml
creation_rules:
  - path_regex: secrets.yaml
    age: >-
      age17r5w7xddcx6c3n4hrh6wneepurlvkrchj3vfteyxn6kcdlhqev9q8len7u,
      age1gcq879stcmtueu9e4gg8wv5f0znazz60s0zapkf2xk6cydape5cscx4n33
